#!/usr/bin/env python3
"""Build the inflection-dependence contingency table.

Canonical script for the table the abstract reports. Replicates the
Steriade (2008) §10.2.3.5 lexical counts under the appropriate coding
for our data:

ROW
    ``plural alternates`` yes/no, derived from the ``mutation`` field
    of the lexicon CSV (which is the direct singular-vs-plural surface
    comparison: t→ț, d→z, s→ș for coronals; orthographic ci/ce/gi/ge
    for dorsals).

COLUMN
    Verbalizer allomorph (``-i`` vs ``-a``). This is Steriade's affix-
    avoidance tabulation in her (10.20). We do not filter the column by
    whether the verb's conjugated paradigm independently surfaces the
    alternation — that is a separate (manifestation b) question, and
    Steriade is explicit that it does not arise with derived verbs.

EXCLUSIONS
    - Rows whose ``exception_reason`` begins with ``nde:`` (the three
      non-derived-environment-blocking classes Steriade also excludes).
    - Derived verbs that don't pass the DEX etymology audit. The audit
      categorizations are persisted in
      ``data/derived_verb_etymology.csv`` (the canonical pipeline
      artifact); only categories A, B, D are accepted. See
      :mod:`romanian_palatalization.dex_etymology` for the category
      definitions.
    - Explicit USER_KEEP allowlist for back-formations the etym audit
      mis-rejects: clint, dinte, vargă, verigă.

Etymology source of truth
-------------------------
This script reads etymology decisions from
``data/derived_verb_etymology.csv``, NOT from the live ``dex_cache.db``.
That CSV is generated by the etymology-audit pipeline (one row per
(noun, verb) pair, plus USER_KEEP overrides). Decoupling analysis from
the live cache means the table is reproducible without re-fetching
DEX, and new (noun, verb) pairs that are missing from the CSV are
flagged explicitly rather than silently dropped.

The output is two panels — TOP-1000 most-frequent noun lemmas and FULL
DEX (no frequency filter) — each split into dorsal (c, g), coronal
(t, d, s), and pooled subpanels.

Important methodological note
-----------------------------
The row coding here is ``mutation``-based, NOT the historic
``opportunity``-based allomorph proxy ``-i/-e`` vs ``-uri``. For
coronals, the surface allomorph "-e" does not trigger assibilation
(e.g. *casă/case* does not alternate), so coding by allomorph
mis-classifies coronal -e nouns as alternating. The ``mutation`` field
records the actual sg-vs-pl comparison, which is what Steriade's K/TS
vs K/K split is about.
"""

from __future__ import annotations

import csv
import sys
from collections import Counter
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Callable, Final

from scipy.stats import fisher_exact

# Add src to path so we can import the shared etymology + cache helpers.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT / "src"))

from dex_etymology import USER_KEEP  # noqa: E402

# ---------------------------------------------------------------------------
# Inputs / outputs
# ---------------------------------------------------------------------------

CSV_PATH: Final[Path] = (
    _PROJECT_ROOT / "data" / "romanian_lexicon_with_freq.csv"
)
ETYMOLOGY_CSV_PATH: Final[Path] = (
    _PROJECT_ROOT / "data" / "derived_verb_etymology.csv"
)
OUTPUT_PATH: Final[Path] = _PROJECT_ROOT / "analysis" / "contingency_table.txt"

TOP_N_FREQUENCY: Final[int] = 1_000

DORSAL_STEMS: Final[frozenset[str]] = frozenset({"c", "g"})
CORONAL_STEMS: Final[frozenset[str]] = frozenset({"t", "d", "s"})
TARGET_STEMS: Final[frozenset[str]] = DORSAL_STEMS | CORONAL_STEMS
PLURAL_FRONT_OPPS: Final[frozenset[str]] = frozenset({"i", "e"})
ACCEPTED_VERBALIZERS: Final[frozenset[str]] = frozenset({"-i", "-a"})


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------


class StemClass(StrEnum):
    """Articulatory class of the noun stem-final consonant."""

    DORSAL = "dorsal"
    CORONAL = "coronal"


class PluralAlt(StrEnum):
    """Whether the noun's plural form palatalizes the stem-final."""

    ALTERNATES = "alt"
    NON_ALTERNATING = "nonalt"


class Verbalizer(StrEnum):
    """Verbalizer allomorph the derived verb selects."""

    FRONT_I = "i"
    BACK_A = "a"


@dataclass(frozen=True, slots=True)
class NounRecord:
    """A single noun row that passes the contingency-table row filters.

    Frozen + slots: this object flows between layers and shouldn't
    mutate. ``derived_verbs`` is a tuple so the dataclass is hashable
    if the caller needs it.
    """

    lemma: str
    derived_verbs: tuple[str, ...]
    stem_final: str
    opportunity: str
    deriv_suffix: str  # "-i" or "-a"
    mutation: bool
    frequency: float

    @property
    def stem_class(self) -> StemClass:
        return (
            StemClass.DORSAL
            if self.stem_final in DORSAL_STEMS
            else StemClass.CORONAL
        )

    @property
    def plural_alt(self) -> PluralAlt:
        return (
            PluralAlt.ALTERNATES
            if self.mutation
            else PluralAlt.NON_ALTERNATING
        )

    @property
    def verbalizer(self) -> Verbalizer:
        return (
            Verbalizer.FRONT_I
            if self.deriv_suffix == "-i"
            else Verbalizer.BACK_A
        )


@dataclass(frozen=True, slots=True)
class PanelStats:
    """Fisher 2x2 result for one stem-class panel."""

    alt_i: int
    alt_a: int
    nonalt_i: int
    nonalt_a: int

    @property
    def n(self) -> int:
        return self.alt_i + self.alt_a + self.nonalt_i + self.nonalt_a

    @property
    def is_complete(self) -> bool:
        """All four marginals non-zero (required by Fisher's exact)."""
        return (
            self.alt_i + self.alt_a > 0
            and self.nonalt_i + self.nonalt_a > 0
            and self.alt_i + self.nonalt_i > 0
            and self.alt_a + self.nonalt_a > 0
        )

    def fisher(self) -> tuple[float, float] | None:
        if not self.is_complete:
            return None
        odds, p = fisher_exact(
            [[self.alt_i, self.alt_a], [self.nonalt_i, self.nonalt_a]]
        )
        return float(odds), float(p)

    def format_line(self, name: str) -> str:
        head = (
            f"  {name:8s}:  alt-pl  {self.alt_i:3d}  -i / "
            f"{self.alt_a:3d}  -a    "
            f"nonalt-pl  {self.nonalt_i:3d}  -i / "
            f"{self.nonalt_a:3d}  -a    n = {self.n:4d}"
        )
        fisher = self.fisher()
        if fisher is None:
            return head
        odds, p = fisher
        # Use scientific notation for vanishingly small p so highly
        # significant results don't collapse to "0.000" in the report.
        p_fmt = f"{p:.2e}" if p < 1e-3 else f"{p:.3f}"
        return f"{head}    OR = {odds:.2f}    p = {p_fmt}"


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def _load_records() -> tuple[list[NounRecord], dict[str, float]]:
    """Read the lexicon CSV and return:
    - the NounRecord list passing the row filters
    - a {lemma → frequency} dict for ALL nouns (needed for top-N ranking
      independently of whether the noun is in the contingency table)

    Filters applied here (the trust boundary):
      pos == "N"
      stem_final in TARGET_STEMS
      mutation field is non-empty
      opportunity in {i, e, uri}
      deriv_suffix in {-i, -a}
      derived_verbs non-empty
      exception_reason not starting with "nde:"
    """
    records: list[NounRecord] = []
    seen: set[str] = set()
    frequency_by_lemma: dict[str, float] = {}

    with CSV_PATH.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["pos"] != "N":
                continue
            lemma = row["lemma"]
            try:
                freq = float(row.get("freq_ron_news_2024_1M") or 0)
            except ValueError:
                freq = 0.0
            frequency_by_lemma[lemma] = freq

            stem_final = row["stem_final"]
            if stem_final not in TARGET_STEMS:
                continue
            if row["mutation"].strip() == "":
                continue
            opp = row["opportunity"].strip()
            if opp not in PLURAL_FRONT_OPPS and opp != "uri":
                continue
            deriv_suffix = row["deriv_suffixes"].strip()
            if deriv_suffix not in ACCEPTED_VERBALIZERS:
                continue
            derived_verbs_field = (row.get("derived_verbs") or "").strip()
            if not derived_verbs_field:
                continue
            if (row.get("exception_reason") or "").startswith("nde:"):
                continue
            if lemma in seen:
                continue
            seen.add(lemma)
            verbs = tuple(
                v.strip() for v in derived_verbs_field.split("|") if v.strip()
            )
            records.append(
                NounRecord(
                    lemma=lemma,
                    derived_verbs=verbs,
                    stem_final=stem_final,
                    opportunity=opp,
                    deriv_suffix=deriv_suffix,
                    mutation=row["mutation"].strip().upper() == "TRUE",
                    frequency=freq,
                )
            )
    return records, frequency_by_lemma


# ---------------------------------------------------------------------------
# Etymology audit
# ---------------------------------------------------------------------------


def _load_etymology_decisions() -> (
    tuple[dict[tuple[str, str], bool], set[str]]
):
    """Read the structured etymology CSV into:

    - ``accepted_by_pair``: ``{(noun, verb): True/False}`` from explicit
      audit rows. ``True`` iff the audit categorized the pair as A, B,
      or D (the ACCEPT set). Pairs absent from this map are
      ``unclassified`` — the script will flag them rather than
      silently treat them as rejected.
    - ``user_keep``: set of nouns the explicit user-override list keeps
      regardless of any individual verb's audit result.

    The CSV is the canonical pipeline artifact; this function is the
    single read path. See :mod:`romanian_palatalization.dex_etymology`
    for the underlying category definitions.
    """
    accepted: dict[tuple[str, str], bool] = {}
    user_keep: set[str] = set()
    with ETYMOLOGY_CSV_PATH.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            noun = (row.get("noun") or "").strip()
            verb = (row.get("verb") or "").strip()
            cat = (row.get("category") or "").strip().upper()
            is_acc = (row.get("accepted") or "").strip().lower() == "true"
            if cat == "USER_KEEP":
                user_keep.add(noun)
                continue
            if noun and verb:
                accepted[(noun, verb)] = is_acc
    # Merge in the hard-coded fallback so a missing CSV doesn't silently
    # drop the back-formation overrides.
    user_keep |= set(USER_KEEP)
    return accepted, user_keep


def _passes_etymology_audit(
    record: NounRecord,
    accepted_by_pair: dict[tuple[str, str], bool],
    user_keep: set[str],
    unclassified_pairs: set[tuple[str, str]],
) -> bool:
    """At least one derived verb must be ACCEPTED in the etymology CSV,
    OR the lemma must appear in ``user_keep``.

    ``unclassified_pairs`` is mutated in place: any (noun, verb) pair
    not present in ``accepted_by_pair`` is added so the caller can warn
    about coverage gaps after the run.
    """
    if record.lemma in user_keep:
        return True
    for verb in record.derived_verbs:
        key = (record.lemma, verb)
        if key not in accepted_by_pair:
            unclassified_pairs.add(key)
            continue
        if accepted_by_pair[key]:
            return True
    return False


# ---------------------------------------------------------------------------
# Table building
# ---------------------------------------------------------------------------


_ScopeFilter = Callable[[NounRecord], bool]


def _build_panels(
    records: list[NounRecord],
    accepted_by_pair: dict[tuple[str, str], bool],
    user_keep: set[str],
    unclassified_pairs: set[tuple[str, str]],
    scope: _ScopeFilter,
) -> tuple[dict[StemClass | str, PanelStats], int]:
    """Build dorsal, coronal, and pooled panels for the records that
    pass ``scope`` and the etymology audit.

    Returns the three panels keyed by ``StemClass`` plus a sentinel
    "pooled" string, and the count of kept records.
    """
    cells: dict[StemClass | str, Counter[tuple[PluralAlt, Verbalizer]]] = {
        StemClass.DORSAL: Counter(),
        StemClass.CORONAL: Counter(),
        "pooled": Counter(),
    }
    n_kept = 0
    for record in records:
        if not scope(record):
            continue
        if not _passes_etymology_audit(
            record, accepted_by_pair, user_keep, unclassified_pairs
        ):
            continue
        n_kept += 1
        key = (record.plural_alt, record.verbalizer)
        cells[record.stem_class][key] += 1
        cells["pooled"][key] += 1

    def pack(c: Counter[tuple[PluralAlt, Verbalizer]]) -> PanelStats:
        return PanelStats(
            alt_i=c[(PluralAlt.ALTERNATES, Verbalizer.FRONT_I)],
            alt_a=c[(PluralAlt.ALTERNATES, Verbalizer.BACK_A)],
            nonalt_i=c[(PluralAlt.NON_ALTERNATING, Verbalizer.FRONT_I)],
            nonalt_a=c[(PluralAlt.NON_ALTERNATING, Verbalizer.BACK_A)],
        )

    return (
        {k: pack(v) for k, v in cells.items()},
        n_kept,
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def _render_report(
    records: list[NounRecord],
    accepted_by_pair: dict[tuple[str, str], bool],
    user_keep: set[str],
    unclassified_pairs: set[tuple[str, str]],
    frequency_by_lemma: dict[str, float],
) -> str:
    """Render the contingency-table report to a string.

    Two panels: TOP-{TOP_N_FREQUENCY} and FULL DEX, each split into
    dorsal, coronal, and pooled subpanels. Returns the full text
    output that gets both printed and persisted.
    """
    lines: list[str] = []
    lines.append(
        f"Loaded {len(records)} (lemma, dvs, ...) tuples "
        f"that pass row filters."
    )
    lines.append(
        f"Etymology decisions: {len(accepted_by_pair)} explicit pairs, "
        f"{len(user_keep)} user-keep lemmas."
    )

    ranked = sorted(frequency_by_lemma.items(), key=lambda kv: -kv[1])
    top_lemmas: frozenset[str] = frozenset(
        lemma for lemma, _ in ranked[:TOP_N_FREQUENCY]
    )

    scopes: list[tuple[str, _ScopeFilter]] = [
        (f"TOP-{TOP_N_FREQUENCY}", lambda r: r.lemma in top_lemmas),
        ("FULL DEX", lambda r: True),
    ]

    lines.append("\n" + "=" * 78)
    lines.append(
        "Contingency table: row = plural alternates (mutation),"
        " column = verbalizer allomorph"
    )
    lines.append("=" * 78)
    for label, scope in scopes:
        panels, n_kept = _build_panels(
            records,
            accepted_by_pair,
            user_keep,
            unclassified_pairs,
            scope,
        )
        lines.append(f"\n{label}  (n_kept = {n_kept})")
        for name in (StemClass.DORSAL, StemClass.CORONAL, "pooled"):
            stats = panels[name]
            display = name.value if isinstance(name, StemClass) else name
            lines.append(stats.format_line(display))
    return "\n".join(lines) + "\n"


def main() -> None:
    records, frequency_by_lemma = _load_records()
    accepted_by_pair, user_keep = _load_etymology_decisions()
    unclassified_pairs: set[tuple[str, str]] = set()

    report = _render_report(
        records,
        accepted_by_pair,
        user_keep,
        unclassified_pairs,
        frequency_by_lemma,
    )
    print(report, end="")

    # Persist the report so future runs can be compared without re-
    # running the script (e.g., when the user edits derived verbs).
    OUTPUT_PATH.write_text(report, encoding="utf-8")
    print(f"\nReport persisted to {OUTPUT_PATH}")

    if unclassified_pairs:
        # Coverage gap: pairs in the lexicon that are missing from
        # the etymology CSV. Print a concise summary so the user knows
        # the etymology audit needs a refresh on these.
        n = len(unclassified_pairs)
        sample = sorted(unclassified_pairs)[:10]
        print(
            f"\nWARNING: {n} (noun, verb) pairs lack an etymology "
            f"classification in {ETYMOLOGY_CSV_PATH.name}."
        )
        print("First 10 unclassified pairs:")
        for noun, verb in sample:
            print(f"  {noun}  →  {verb}")
        print(
            "To refresh, re-run the supplement step or add the missing "
            "rows to the etymology CSV with category in {A, B, D} "
            "(accepted) or {C, E, F} (rejected)."
        )


if __name__ == "__main__":
    main()
